### ISSUE TITLE
More jsonSchema woes with Typescript

### ISSUE THREAD

**Issue by imwillhang** [Vincit/objection.js#1636]
Thanks so much for your help. We were happily deploying objection 1.6.11 in production with Typescript until we upgraded to 2.0.10, and everything went down from there.

My issue is that:
**After updating from objection 1.6.11 to 2.0.10, I am seeing the following Typescript errors coming from our Model declarations. We had received no issues prior to the upgrade.**

```
src/db/models/ExampleTable.ts(4,7): error TS2417: Class static side 'typeof ExampleTable' incorrectly extends base class static side 'typeof Model'.
Types of property 'jsonSchema' are incompatible.
    Type '{ properties: { id: { type: string; }; property1: { type: string; }; property2: { type: string; }; property3: { type: string; }; }; type: string; }' is not assignable to type 'JSONSchema'.
        Types of property 'type' are incompatible.
            Type 'string' is not assignable to type '"string" | "number" | "boolean" | "object" | "integer" | "array" | "null" | JSONSchemaTypeName[]'.
```

- We are on the latest version of Knex
- I am aware of issue #1615 and have a feeling that it is related. However, I could not find a way to import the JSONSchema type to cast `jsonSchema` to.

Here is an example of our Model declaration file:

```
import objection from "objection";
import path from "path";

class ExampleTable extends objection.Model {
	public id?: number;
	public property1: number;
	public property2?: object;
	public property3?: object;

	static get tableName() {
		return "exampletable";
	}

	static get idColumn() {
		return "id";
	}

	static get jsonSchema() {
		return {
			properties: {
				id: { type: "integer" },
				property1: { type: "integer" },
				property2: { type: "string" },
				property3: { type: "string" },
			},
			type: "object"
		};
	}
}
export default ExampleTable;
```

Thank you again!

**Comment by koskimas** [comment]
```
static get jsonSchema(): JSONSchema {
```
The new json schema typings are more strict and you need to add the explicit type telling typescript that some strings are in fact enums.

> until we upgraded to 2.0.10, and everything went down from there.

That's quite dramatic 😀 What else is broken?

**Comment by imwillhang** [comment]
Thank you so much, I will try this very soon. That's the major thing, it really blew up all of our Models, but thanks so much for the help and I hope this issue helps everyone else upgrading + using Typescript!

**Comment by koskimas** [comment]
@imwillhang I just released a new version that no longer requires the explicit type. It was more trouble than it was worth.

**Comment by imwillhang** [comment]
Incredible, thank you so much! I'll try to upgrade now and I'll let you know what happens.

**Comment by imwillhang** [comment]
Ah, _so close_! I upgraded to 2.1.0, and everything seems to work smoothly **except...**

```await parent.$relatedQuery("children");```

no longer populates the original object `parent` with the field `children`, whereas it did before in version 1.6.11. Is this behavior intended? Absolutely no DB or Model changes occurred in between the versions.

**Comment by koskimas** [comment]
@imwillhang **Read the changelog please**

**Comment by koskimas** [comment]
https://vincit.github.io/objection.js/1.x/migration.html#relatedquery-no-longer-mutates

**Comment by imwillhang** [comment]
Oh man, thank you! Sorry for not looking here earlier, hope this helps everyone else as well.
