### ISSUE TITLE
Problem with $relatedQuery typings

### ISSUE THREAD

**Issue by chamini2** [Vincit/objection.js#856]
If I have:

```ts

class One extends Model {
  public static get relationMappings(): RelationMappings {
    return {
      twos: {
        relation: Model.HasManyRelation,
        modelClass: Two,
        join: { from: 'ones.id', to: 'twos.one_id' }
      }
    };
  }

  public twos: Two[];
}

class Two extends Model {
  id: number;
}

function a() {
  const one = new One();
  one.$relatedQuery('twos')
  .insert([{ id: 1 }]);
}

```

It will throw at compile the following:

```
error TS2345: Argument of type '{ id: number; }[]' is not assignable to parameter of type 'Partial<Two[] & Model> | undefined'.
  Type '{ id: number; }[]' is not assignable to type 'Partial<Two[] & Model>'.
    Types of property 'push' are incompatible.
      Type '(...items: { id: number; }[]) => number' is not assignable to type '((...items: Two[]) => number) | undefined'.
        Type '(...items: { id: number; }[]) => number' is not assignable to type '(...items: Two[]) => number'.
          Types of parameters 'items' and 'items' are incompatible.
            Type 'Two' is not assignable to type '{ id: number; }'.
              Property '$id' does not exist on type '{ id: number; }'.
```

I think this problem was introduced in https://github.com/Vincit/objection.js/pull/773:

> QM now always extends Model. I believe this is correct, right? Can you query on non-models?

**Comment by chamini2** [comment]
It does type check, although it still looks like a hack.

**Comment by douggr** [comment]
Actually, `public twos: Two[];` should be `public twos: Two`. It's handled it internally somehow.

```ts
export default class User extends Model {
  public static readonly relationMappings = {
    emails: {
      join: {
        from: "user.id",
        to: "email.user_id",
      },
      modelClass: Email,
      relation: Model.HasManyRelation,
    },
  };

  public emails?: Email;
}
```

```ts
  User.query().findById(1).then((r) => {
    if (!r) {
      throw new Error("Not Found");
    }

    return r.$relatedQuery("emails")
      .insert([
        { email: Math.random().toString(36).substring(7) },
        { email: Math.random().toString(36).substring(7) },
        { email: Math.random().toString(36).substring(7) },
      ])
      .returning("*")
      .then((rs) => res.jsonp(rs));
  });

  // and loading... 
    User.query()
    .findById(1)
    .eager("emails")
    .then((r) => res.jsonp(r));

```

**Comment by douggr** [comment]
Regarding loading, this works for a single record:

```ts
User.query()
  .findById(1)
  .eager("emails")
  .then((r) => res.jsonp(r));
```

But if you load a whole rowset, you need to loop through it because relations will not expand, I'm not sure if this is the expected, @koskimas can you confirm this behavior please?

```ts
User.query()
  .eager("emails")
  .then((rowset) => {
    // return res.jsonp(rowset); // emails will not expand here

    const json = [];
    rowset.forEach(row => json.push(row));

    // res is a Express.Response
    return res.jsonp(json);
  });
```

Simple examples here: https://github.com/douggr/objection-issues-examples

**Comment by koskimas** [comment]
@douggr No need to loop through relations like that.

**Comment by koskimas** [comment]
This is fixed in 2.0 branch.
