### ISSUE TITLE
typings don't work with typescript 2.7

### ISSUE THREAD

**Issue by koskimas** [Vincit/objection.js#772]
This is the error:

```
tests/ts/examples.ts(41,3): error TS2564: Property 'firstName' has no initializer and is not definitely assigned in the constructor.
tests/ts/examples.ts(42,3): error TS2564: Property 'lastName' has no initializer and is not definitely assigned in the constructor.
tests/ts/examples.ts(43,3): error TS2564: Property 'mom' has no initializer and is not definitely assigned in the constructor.
tests/ts/examples.ts(44,3): error TS2564: Property 'children' has no initializer and is not definitely assigned in the constructor.
tests/ts/examples.ts(45,3): error TS2564: Property 'pets' has no initializer and is not definitely assigned in the constructor.
tests/ts/examples.ts(46,3): error TS2564: Property 'comments' has no initializer and is not definitely assigned in the constructor.
tests/ts/examples.ts(47,3): error TS2564: Property 'movies' has no initializer and is not definitely assigned in the constructor.
tests/ts/examples.ts(163,3): error TS2564: Property 'title' has no initializer and is not definitely assigned in the constructor.
tests/ts/examples.ts(164,3): error TS2564: Property 'actors' has no initializer and is not definitely assigned in the constructor.
tests/ts/examples.ts(165,3): error TS2564: Property 'director' has no initializer and is not definitely assigned in the constructor.
tests/ts/examples.ts(214,3): error TS2564: Property 'species' has no initializer and is not definitely assigned in the constructor.
tests/ts/examples.ts(229,3): error TS2564: Property 'comment' has no initializer and is not definitely assigned in the constructor.
tests/ts/examples.ts(271,3): error TS2564: Property 'canAct' has no initializer and is not definitely assigned in the constructor.
tests/ts/examples.ts(292,72): error TS2345: Argument of type 'typeof Person' is not assignable to parameter of type 'ModelClass<Model>'.
  Type 'Person' is not assignable to type 'Model'.
    Types of property '$setJson' are incompatible.
      Type '(json: Pojo, opt?: ModelOptions | undefined) => Person' is not assignable to type '(json: Pojo, opt?: ModelOptions | undefined) => Model'.
        Type 'Person' is not assignable to type 'Model'.
```

@mceachen Could you take a look at this at some point?

**Comment by mceachen** [comment]
Huh, lots of new stuff: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html

**Comment by mceachen** [comment]
OMG TS 2.8 BRINGS CONDITIONAL TYPES https://github.com/Microsoft/TypeScript/pull/21316

ok now to see about a fix

**Comment by mceachen** [comment]
@koskimas a good deal of dependencies in package.json are out of date, fwiw. Do you want a PR to update that?

```diff
diff --git a/package.json b/package.json                   
index 4968425..814114a 100644                              
--- a/package.json                                         
+++ b/package.json                                         
@@ -56,32 +56,32 @@                                        
   ],                                                      
   "types": "./typings/objection/index.d.ts",              
   "dependencies": {                                       
-    "ajv": "^6.0.1",                                      
+    "ajv": "^6.1.1",                                      
     "bluebird": "^3.5.1",                                 
     "lodash": "^4.17.4"                                   
   },                                                      
   "peerDependencies": {                                   
-    "knex": "0.x"                                         
+    "knex": "^0.14.2"                                     
   },                                                      
   "devDependencies": {                                    
-    "@types/knex": "^0.0.67",                             
-    "@types/node": "^8.0.57",                             
-    "babel-eslint": "^8.0.1",                             
+    "@types/knex": "^0.14.5",                             
+    "@types/node": "^9.4.0",                              
+    "babel-eslint": "^8.2.1",                             
     "chai": "^4.1.2",                                     
     "chai-subset": "^1.6.0",                              
     "coveralls": "^3.0.0",                                
-    "eslint": "^4.10.0",                                  
-    "eslint-plugin-prettier": "^2.3.1",                   
+    "eslint": "^4.16.0",                                  
+    "eslint-plugin-prettier": "^2.5.0",                   
     "expect.js": "^0.3.1",                                
-    "fs-extra": "5.0.0",                                  
-    "glob": "^7.1.1",                                     
+    "fs-extra": "^5.0.0",                                 
+    "glob": "^7.1.2",                                     
     "istanbul": "^0.4.5",                                 
-    "knex": "0.x",                                        
-    "mocha": "^4.0.1",                                    
-    "mysql": "^2.13.0",                                   
-    "pg": "^7.4.0",                                       
-    "prettier": "^1.9.1",                                 
-    "sqlite3": "3.1.13",                                  
-    "typescript": "2.6.2"                                 
+    "knex": "^0.14.2",                                    
+    "mocha": "^5.0.0",                                    
+    "mysql": "^2.15.0",                                   
+    "pg": "^7.4.1",                                       
+    "prettier": "^1.10.2",                                
+    "sqlite3": "^3.1.13",                                 
+    "typescript": "^2.7.1"                                
   }                                                       
 }                                                         
```

**Comment by koskimas** [comment]
@mceachen Sure!

**Comment by mceachen** [comment]
fwiw I'm just running `salita -u` and `yarn`.

**Comment by koskimas** [comment]
If you want to do that too, then sure. I can do that later if you don't want to.

**Comment by mceachen** [comment]
All the other errors are simple, it's just field optionality. The `$setJson` error is a bit more involved.
